### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by cashelcomputers** [tcannonfodder/houston#1]
Hi,
Upon loading index.html, the only data that is displayed is MET and UT. When I open up the web console I am seeing several" downloadable font: download failed" messages, and finally at the end after about 2 seconds after page load, the message "NetworkError: A network error occurred." I've attached a screenshot if that helps.

Cheers,
Tim
![screenshot at 2016-04-12 16 57 04](https://cloud.githubusercontent.com/assets/6221698/14450169/ade5be32-00cf-11e6-8639-f85c26bcdeda.png)

**Comment by tcannonfodder** [comment]
Hey Tim!

The first thing I notice is that you're using Firefox. Houston only supports Webkit browsers at this time (mainly because I haven't had the time to make it compatible). Can you try on a webkit browser like Chrome and let me know if you're still running into issues?

Btw, if you'd like to make Houston work on Firefox, feel free to fork it make a PR! :)

**Comment by cashelcomputers** [comment]
Hey, yea I'll have a crack at installing chrome and give it a go. I can certainly have a look at the reason it's not working in Firefox, my web programming kungfu is rudimentary at best though.
Cheers!
